language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.5"

dist: trusty

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - test

jobs:
  include:
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"
env:
  global:
    - VERSION="11.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    - WKHTMLTOPDF_VERSION="0.12.5"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - git clone --depth=1
    https://${CI_USER_TOKEN}:x-oauth-basic@github.com/open-synergy/oe.git
    ${HOME}/dependencies/oe

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
